CREATE TABLE PRODUTOS
(
 ID INT,
 NOME VARCHAR(20) NOT NULL,
 ID_CATEGORIA INT NOT NULL,
 PRECO DOUBLE NOT NULL
)

ALTER TABLE PRODUTOS ADD INDEX (ID);

ALTER TABLE PRODUTOS CHANGE ID ID INT AUTO_INCREMENT;