CREATE TABLE `Produtos`(
`id` INTEGER PRIMARY KEY  AUTOINCREMENT,
 `nome` VARCHAR(255) NOT NULL,
 `fkCategoria` BIGINT NOT NULL,
 `preco` DECIMAL NOT NULL,
 FOREIGN KEY(`fkCategoria`) REFERENCES `Categoria`(`id`)
);