<<<<<<< HEAD
CREATE TABLE CUPONS
(
ID INT, 
NOME VARCHAR(20) NOT NULL,
DESCONTO_ASSOCIADO DOUBLE NOT NULL
)

ALTER TABLE CUPONS ADD INDEX (ID);

ALTER TABLE CUPONS CHANGE ID ID INT AUTO_INCREMENT;
=======
SELECT 'SUBTITUA O CONTEÚDO DESTE ARQUIVO PELA SUA RESPOSTA :-)';
>>>>>>> ee682c089f27d0d5e4ab9981814c7d4be8be59be
