<<<<<<< HEAD
CREATE TABLE CATEGORIAS
(
ID INT PRIMARY KEY AUTO_INCREMENT, 
NOME VARCHAR(20) NOT NULL,
DESCONTO_ASSOCIADO DOUBLE 
)
=======
SELECT 'SUBTITUA O CONTEÚDO DESTE ARQUIVO PELA SUA RESPOSTA :-)';
>>>>>>> ee682c089f27d0d5e4ab9981814c7d4be8be59be
